[versions]
aboutLibraries = "13.2.1"
android-desugar = "2.1.5"
android-gradle = "8.13.2"
androidx-activity-compose = "1.13.0"
androidx-annotation = "1.9.1"
androidx-appCompat = "1.7.1"
androidx-benchmark = "1.4.1"
androidx-biometric = "1.2.0-alpha05"
androidx-compose-bom = "2026.03.01"
androidx-constraintLayout = "2.2.1"
androidx-core = "1.18.0"
androidx-coreSplashScreen = "1.2.0"
androidx-glance = "1.1.1"
androidx-interpolator = "1.0.0"
androidx-lifecycle = "2.10.0"
androidx-paging = "3.4.2"
androidx-preference = "1.2.1"
androidx-profileInstaller = "1.4.1"
androidx-recyclerView = "1.4.0"
androidx-sqlite = "2.6.2"
androidx-test-espresso = "3.7.0"
androidx-test-junit = "1.3.0"
androidx-test-uiautomator = "2.3.0"
androidx-viewPager = "1.1.0"
androidx-work = "2.11.2"
archive = "1.1.6"
coil = "3.4.0"
composeGrid = "1.2.2"
composeMaterialMotion = "2.0.1"
composeRichEditor = "1.0.0-rc13"
composeWebview = "0.33.6"
conscrypt = "2.5.3"
directionalViewPager = "1.0.0"
diskLruCache = "2.0.2"
firebase-bom = "34.11.0"
firebase-crashlytics = "3.0.6"
flexibleAdapter = "c8013533"
google-services = "4.4.4"
image-decoder = "41c059e540"
injekt = "91edab2317"
jsoup = "1.22.1"
junit = "6.0.3"
kotest-assertions = "6.1.10"
kotlin-gradle = "2.3.20"
kotlinx-collections-immutable = "0.4.0"
kotlinx-coroutines = "1.10.2"
kotlinx-serialization = "1.10.0"
ktlint = "1.8.0"
leakCanary = "2.14"
logcat = "0.4"
markdown = "0.39.2"
material = "1.12.0"
materialKolor = "5.0.0-alpha07"
mockk = "1.14.9"
moko-resources = "0.26.1"
okhttp = "5.3.2"
okio = "3.17.0"
photoView = "2.3.0"
quickJs = "547f5b1597"
reorderable = "3.0.0"
rxJava = "1.3.8"
shizuku = "13.1.5"
spotless = "8.4.0"
sqldelight = "2.3.2"
sqldelight-androidx-driver = "0.0.17"
stringSimilarity = "0.1.0"
subsamplingScaleImageView = "66e0db195d"
swipe = "1.3.0"
tapmoc = "0.4.1"
unifile = "e0def6b3dc"
voyager = "1.1.0-beta03"
xmlutil = "0.91.3"
